version: '3.12'

services:
  web:
    build: .
    container_name: radsolutions_web
    command: gunicorn --bind 0.0.0.0:8000 app_server.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: radsolutions_db
    restart: always
    environment:
      POSTGRES_DB: radsolutions_db
      POSTGRES_USER: radsolutions_user
      POSTGRES_PASSWORD: radsolutions_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
