name: Django Tests and Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Create .env file
      run: |
        echo "DATABASE_NAME=radsolutions_db" >> .env
        echo "DATABASE_USER=radsolutions_user" >> .env
        echo "DATABASE_PASSWORD=radsolutions_pass" >> .env
        echo "DATABASE_HOST=db" >> .env
        echo "DATABASE_PORT=5432" >> .env
        echo "DEBUG=True" >> .env
        echo "DJANGO_SECRET_KEY='django-insecure-k#cb*25^f8d9js*%rnkjc24_^r^(8#-@$m*8ia1-zn*ytg=#u*'" >> .env
    
    - name: Build and start Docker containers
      run: |
        docker compose up -d db
        docker compose build web
    
    - name: Install linting tools in container
      run: |
        docker compose run --rm web pip install isort flake8 black
    
    - name: Run Django tests in container
      run: |
        docker compose run --rm web python manage.py test
    
    - name: Run isort check in container
      run: |
        docker compose run --rm web isort . --check
    
    - name: Run black check in container
      run: |
        docker compose run --rm web black . --check
    
    - name: Run flake8 in container
      run: |
        docker compose run --rm web flake8 .
    
    - name: Stop containers
      run: |
        docker compose down 